### ISSUE TITLE
Se possível fazer um Guide de como usar

### ISSUE THREAD

**Issue by dpaes** [oriondesign2015/n8n-nodes-evolution-api#1]
Acabei de instalar no meu n8n, porém ele fica aparecendo no log que precisa de credencial, porém não cheguei a passar nada, só instalei via docker no meu n8n, criando a pasta .n8n/nodes e instalando o package dentro, porém to meio perdido.
Achei interessante pra poder testar o 2.0 ja que ja tenho um evo no meu vps, mas queria testar o 2.0 e sepa vou conseguir via n8n
Se puder fazer um passo a passo pra poder visualizar o Gui ou a Cli mesmo pra poder ver se ta rodando ou como configurar seria top. Abraço

**Comment by oriondesign2015** [comment]
Olá @dpaes, tudo bem?
As credenciais que pede é o Endpoint da sua Evolution API e sua Global API key, as mesmas informações que você usa para acessar o /manager da EvolutionAPI.

O node atualmente esta em desenvolvimento e por conta disso não terá nenhum video tutorial do mesmo. a não ser a partir do dia 10/08 que vai sair a primeira versão 1.0.0 do Node.

Junte-se aos nossos grupos no WhatsApp e troque conhecimento ou tire suas dúvidas com nossos membros:
Grupo #01 - SetupOrion
https://oriondesign.art.br/whatsapp1

Grupo #02 - 🆕 SetupOrion
https://oriondesign.art.br/whatsapp2

**Comment by dpaes** [comment]
entendi, desculpe me antecipar demais, é pq achei o package no n8n-community dai pensei q ja tava funcionando hehehe
